import { v4 as uuid } from "uuid";
import {
    tshirt1,
    tshirt2,
    tshirt3,
    tshirt4,
    tshirt5,
    casualShirt1,
    casualShirt3,
    casualShirt2,
    formalShirt1,
    formalShirt2,
    formalShirt3,
    jeans1,
    jeans2,
    jeans3,
    trouser1,
    trouser2,
    trouser3,
} from "../../assets";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: uuid(),
        title: "Plain White Tshirt",
        categoryName: "TShirt",
        prodImg: tshirt1,
        rating: 5,
        reviews: 488,
        originalPrice: 1200,
        discountPrice: 960,
        discountRate: 20,
    },
    {
        _id: uuid(),
        title: "Solid Cargo Pants",
        categoryName: "Trousers",
        prodImg: trouser2,
        rating: 3.6,
        reviews: 250,
        originalPrice: 3999,
        discountPrice: 1999,
        discountRate: 50,
    },
    {
        _id: uuid(),
        title: "Basic Black Trousers",
        categoryName: "Trousers",
        prodImg: trouser3,
        rating: 2.5,
        reviews: 10,
        originalPrice: 1999,
        discountPrice: 999,
        discountRate: 50,
    },
    {
        _id: uuid(),
        title: "Printed Art Tshirt",
        categoryName: "TShirt",
        prodImg: tshirt2,
        rating: 3.8,
        reviews: 128,
        originalPrice: 1500,
        discountPrice: 1200,
        discountRate: 20,
    },
    {
        _id: uuid(),
        title: "Tealer Maroon Tshirt",
        categoryName: "TShirt",
        prodImg: tshirt3,
        rating: 4.5,
        reviews: 200,
        originalPrice: 3000,
        discountPrice: 1800,
        discountRate: 40,
    },
    {
        _id: uuid(),
        title: "Color-block Shirt",
        categoryName: "CasualShirt",
        prodImg: casualShirt1,
        rating: 3.5,
        reviews: 511,
        originalPrice: 1499,
        discountPrice: 1049,
        discountRate: 30,
    },
    {
        _id: uuid(),
        title: "Striped Tshirt",
        categoryName: "TShirt",
        prodImg: tshirt4,
        rating: 2.9,
        reviews: 88,
        originalPrice: 900,
        discountPrice: 810,
        discountRate: 10,
    },
    {
        _id: uuid(),
        title: "Coloured Tshirts",
        categoryName: "TShirt",
        prodImg: tshirt5,
        rating: 1,
        reviews: 55,
        originalPrice: 1200,
        discountPrice: 900,
        discountRate: 25,
    },
    {
        _id: uuid(),
        title: "Highlander White Shirt",
        categoryName: "CasualShirt",
        prodImg: casualShirt2,
        rating: 4,
        reviews: 852,
        originalPrice: 999,
        discountPrice: 799,
        discountRate: 20,
    },
    {
        _id: uuid(),
        title: "H&M Blue Relaxed Jeans",
        categoryName: "Jeans",
        prodImg: jeans2,
        rating: 4.6,
        reviews: 111,
        originalPrice: 1999,
        discountPrice: 1899,
        discountRate: 10,
    },
    {
        _id: uuid(),
        title: "Highlander Printed Shirt",
        categoryName: "CasualShirt",
        prodImg: casualShirt3,
        rating: 5,
        reviews: 688,
        originalPrice: 1199,
        discountPrice: 899,
        discountRate: 20,
    },

    {
        _id: uuid(),
        title: "INVICTUS White Shirt",
        categoryName: "FormalShirt",
        prodImg: formalShirt1,
        rating: 3.8,
        reviews: 150,
        originalPrice: 1799,
        discountPrice: 899,
        discountRate: 50,
    },
    {
        _id: uuid(),
        title: "Black Stretchable Jeans",
        categoryName: "Jeans",
        prodImg: jeans3,
        rating: 3.8,
        reviews: 25,
        originalPrice: 2499,
        discountPrice: 999,
        discountRate: 60,
    },
    {
        _id: uuid(),
        title: "U.S. Polo Assn. Shirt",
        categoryName: "FormalShirt",
        prodImg: formalShirt2,
        rating: 4,
        reviews: 50,
        originalPrice: 2199,
        discountPrice: 1759,
        discountRate: 20,
    },
    {
        _id: uuid(),
        title: "Plain White Shirt",
        categoryName: "FormalShirt",
        prodImg: formalShirt3,
        rating: 4.8,
        reviews: 250,
        originalPrice: 2099,
        discountPrice: 1469,
        discountRate: 30,
    },

    {
        _id: uuid(),
        title: "Blue Tapered Fit Jeans",
        categoryName: "Jeans",
        prodImg: jeans1,
        rating: 3.5,
        reviews: 300,
        originalPrice: 1899,
        discountPrice: 854,
        discountRate: 50,
    },
    {
        _id: uuid(),
        title: "Plain Blue Trousers",
        categoryName: "Trousers",
        prodImg: trouser1,
        rating: 4.8,
        reviews: 290,
        originalPrice: 2599,
        discountPrice: 1559,
        discountRate: 40,
    },
];
